---
- name: Create pki directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ k8s_pki_dir }}"
    - "{{ etcd_pki_dir }}"
    - "{{ user_accounts_pki_dir }}"
  tags:
    - always

- name: Etcd
  import_tasks: etcd.yaml
  tags:
    - etcd

- name: k8s CA
  import_tasks: k8s-ca.yaml
  tags:
    - master
    - k8s-ca

- name: kube-apiserver
  import_tasks: apiserver.yaml
  tags:
    - master
    - kube-apiserver

- name: kube-controller-manager
  import_tasks: controller-manager.yaml
  tags:
    - master
    - kube-controller-manager

- name: kube-scheduler
  import_tasks: scheduler.yaml
  tags:
    - master
    - kube-scheduler

- name: admin account
  import_tasks: admin.yaml
  tags:
    - admin

- name: kubelet
  import_tasks: kubelet.yaml
  tags:
    - node
    - kubelet

- name: kube-proxy
  import_tasks: kube-proxy.yaml
  tags:
    - node
    - kube-proxy
